### ISSUE TITLE
关于模板插件, 给你一个好玩的思路

### ISSUE THREAD

**Issue by lanyuanxiaoyao** [Hatcat123/uTools_WechatDoonsec#1]
翻页做得很有意思, 关于魔改模板插件其实还是有办法的
通过`MutationObserver`可以"hook"每一个列表项, 这样可以根据自定义的内容去渲染出自定义的界面, 还有很有意思的.
效果可以在"资源搜索 Lite"插件里看到, 代码可以在这里找到: [我的操作](https://github.com/LanyuanXiaoyao-Studio/utools-search-lite/blob/master/preload.js#L45)

😜 祝 JavaScript 玩得开心

**Comment by Hatcat123** [comment]
> 翻页做得很有意思, 关于魔改模板插件其实还是有办法的
> 通过`MutationObserver`可以"hook"每一个列表项, 这样可以根据自定义的内容去渲染出自定义的界面, 还有很有意思的.
> 效果可以在"资源搜索 Lite"插件里看到, 代码可以在这里找到: [我的操作](https://github.com/LanyuanXiaoyao-Studio/utools-search-lite/blob/master/preload.js#L45)
> 
> 😜 祝 JavaScript 玩得开心

当初写的时候也参考了你的项目插件，but你的水平太高了，接下来我准备copy你的代码了✏️

**Comment by lanyuanxiaoyao** [comment]
> > 翻页做得很有意思, 关于魔改模板插件其实还是有办法的
> > 通过`MutationObserver`可以"hook"每一个列表项, 这样可以根据自定义的内容去渲染出自定义的界面, 还有很有意思的.
> > 效果可以在"资源搜索 Lite"插件里看到, 代码可以在这里找到: [我的操作](https://github.com/LanyuanXiaoyao-Studio/utools-search-lite/blob/master/preload.js?rgh-link-date=2021-03-17T07%3A42%3A40Z#L45)
> > 😜 祝 JavaScript 玩得开心
> 
> 当初写的时候也参考了你的项目插件，but你的水平太高了，接下来我准备copy你的代码了✏️

其实水平是真的菜, 前端我都是现学的, 那个代码里面封装的东西多了, 跳来跳去的看着不方便, 实际上也就是`MutationObserver`这个原生功能和`nanobar`, `mousetrap`这两个包实现了一些魔改功能, 其他的代码倒是没有什么参考价值了.
